const planets = {
    Nabooh : {
        name: 'Nabooh',
        lat : 10,
        long: 10,       
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Dagobah : {
        name: 'Dagobah',
        lat : 10,
        long: 10,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    DeathStar : {
        name: 'Death Star',
        lat : 10,
        long: 10,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Alderaan : {
        name: 'Alderaan',
        lat : 10,
        long: 10,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Hoth : {
        name: 'Hoth',
        lat : 90,
        long: 0,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Tatooine : {
        name: 'Tatooine',
        lat : 10,
        long: 10,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Mustafar : {
        name: 'Mustafar',
        lat : 24.7742,
        long: 46.7385,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Endor : {
        name: 'Endor',
        lat : 43.3879,
        long: -1.6603,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Felucia : {
        name: 'Felucia',
        lat : -17.5372,
        long: -149.5660,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    },
    Coruscant : {
        name: 'Coruscant',
        lat : 31.5203,
        long: 74.3587,
        shortInfo: {},
        characters : [],
        history : "",
        generalInfo : "",
    }
}

export default planets